import {useEffect,useMemo,useState} from 'react'
import type {Session} from '@supabase/supabase-js'
import {supabase} from '../lib/supabase'
export function Appointment({session,onBack}:{session:Session;onBack:()=>void}){
 const [step,setStep]=useState(0),[name,setName]=useState(''),[busy,setBusy]=useState(true),[error,setError]=useState(''),[sent,setSent]=useState(false)
 const [f,setF]=useState({nationality:'',birth_date:'',phone:'',reason:''})
 useEffect(()=>{(async()=>{try{if(!session.provider_token){setError('Une nouvelle identification est nécessaire.');return}const {data,error:e}=await supabase.functions.invoke('sync-public-identity',{body:{provider_token:session.provider_token}});if(e||!data?.ok)throw e||new Error('Identité indisponible');setName(data.display_name)}catch(e:any){setError(e.message||'Identification impossible')}finally{setBusy(false)}})()},[session])
 const required=useMemo(()=>[name,f.nationality,f.birth_date,f.phone,f.reason.trim().length>=20],[name,f]),progress=Math.round(required.filter(Boolean).length/required.length*100)
 const set=(k:string,v:string)=>setF(x=>({...x,[k]:v}))
 async function submit(){if(progress<100)return setError('Complétez toutes les informations avant l’envoi.');setBusy(true);try{const {data:p}=await supabase.from('public_profiles').select('external_id').eq('auth_user_id',session.user.id).maybeSingle();const {error:e}=await supabase.rpc('submit_appointment',{p_display_name:name,p_nationality:f.nationality,p_birth_date:f.birth_date,p_phone:f.phone,p_reason:f.reason,p_external_id:p?.external_id??null});if(e)throw e;setSent(true)}catch(e:any){setError(e.message||'Envoi impossible')}finally{setBusy(false)}}
 if(sent)return <div className="recruit-shell"><div className="recruit-success"><b>DEMANDE TRANSMISE</b><h1>Rendez-vous enregistré</h1><p>Votre demande a été transmise au service compétent. Vous serez informé directement par message de sa prise en compte.</p><button onClick={onBack}>RETOUR À L'ACCUEIL</button></div></div>
 return <div className="recruit-shell"><header className="recruit-top"><button onClick={onBack}>← ACCUEIL</button><b>DEMANDE DE RENDEZ-VOUS</b><span>{progress}%</span></header><div className="progress"><i style={{width:progress+'%'}}/></div><main className="recruit-card"><div className="stepper">{['Identité','Motif','Vérification'].map((s,i)=><button key={s} className={i===step?'active':''} onClick={()=>setStep(i)}><span>{i+1}</span>{s}</button>)}</div><section className="recruit-form"><small>ÉTAPE {step+1} / 3</small><h1>{['Identité','Motif du rendez-vous','Vérification'][step]}</h1>{busy&&step===0?<p>Récupération de votre identité…</p>:<>{step===0&&<div className="form-grid"><label>Nom et prénom<input value={name} disabled/></label><label>Nationalité<input value={f.nationality} onChange={e=>set('nationality',e.target.value)}/></label><label>Date de naissance<input type="date" value={f.birth_date} onChange={e=>set('birth_date',e.target.value)}/></label><label>Numéro de téléphone<input value={f.phone} onChange={e=>set('phone',e.target.value)}/></label></div>}{step===1&&<label>Motif de votre rendez-vous<textarea rows={12} value={f.reason} onChange={e=>set('reason',e.target.value)} placeholder="Décrivez la raison de votre demande de rendez-vous…"/><small>20 caractères minimum</small></label>}{step===2&&<div className="review"><b>DOSSIER COMPLÉTÉ À {progress}%</b><p><strong>{name}</strong><br/>{f.nationality} · {f.birth_date} · {f.phone}</p><div className="appointment-reason">{f.reason||'Aucun motif renseigné.'}</div></div>}</>}{error&&<div className="public-alert">{error}</div>}<div className="form-nav"><button disabled={step===0} onClick={()=>setStep(x=>Math.max(0,x-1))}>PRÉCÉDENT</button>{step<2?<button onClick={()=>setStep(x=>Math.min(2,x+1))}>SUIVANT</button>:<button disabled={busy||progress<100} onClick={()=>void submit()}>ENVOYER LA DEMANDE</button>}</div></section></main></div>
}