import {useEffect,useMemo,useState} from 'react'
import type {Staff} from '../lib/supabase'
import {chooseBadge,getServiceUnits,joinService,leaveService,signOut,startService,subscribeService} from '../lib/supabase'
import {LogOut,Shield,Users,UserRound,LockKeyhole,Radio} from 'lucide-react'
export function Dashboard({staff}:{staff:Staff}){
 const [units,setUnits]=useState<any[]>([]),[error,setError]=useState(''),[badge,setBadge]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState<'service'|'applications'>('service'),[applications,setApplications]=useState<any[]>([]),[selectedApplication,setSelectedApplication]=useState<any|null>(null)
 const refresh=async()=>{try{setUnits(await getServiceUnits())}catch(e:any){setError(e.message)}}
 useEffect(()=>{void refresh();return subscribeService(()=>void refresh())},[])
 const myUnit=useMemo(()=>units.find(u=>u.service_unit_members?.some((m:any)=>m.staff_id===staff.id)),[units,staff.id])
 const completeAdam=units.some(u=>u.service_type==='adam'&&(u.service_unit_members?.length??0)>=2)
 async function act(fn:()=>Promise<any>){setBusy(true);setError('');try{const r=await fn();if(r?.error)throw r.error;await refresh()}catch(e:any){setError(e.message||'Action impossible')}finally{setBusy(false)}}
 async function saveBadge(){await act(async()=>{const r=await chooseBadge(badge);if(r.error)throw r.error;staff.badge_number=badge.trim();return r})}
 const divisions=staff.divisions??[]
 const manager=staff.app_role==='admin'||staff.app_role==='developer'||staff.rank==='Commandant'||staff.rank==='Commandant adjoint'
 async function loadApplications(){if(!manager)return;const {data}=await (await import('../lib/supabase')).supabase.from('applications').select('*').not('submitted_at','is',null).order('created_at',{ascending:false});setApplications(data??[])}
 async function claim(id:string){setBusy(true);const {error:e}=await (await import('../lib/supabase')).supabase.rpc('claim_application',{p_application:id});if(e)setError(e.message);await loadApplications();setSelectedApplication((x:any)=>x?.id===id?{...x,handled_by:staff.id,status:'reviewing'}:x);setBusy(false)}
 return <div className="portal">
  <header className="portal-top"><div className="wordmark"><span className="mini-shield logo-shell"><img src="https://cdn.picflow.com/assets/images/proxy/full/13da8b62-5943-40f5-9872-a24bd5cbb7f1.webp" alt="Logo LSPD"/></span><div><b>LSPD</b><small>MOBILE DATA TERMINAL</small></div></div><nav><button className={tab==='service'?'active':''} onClick={()=>setTab('service')}>SERVICE</button>{manager&&<button className={tab==='applications'?'active':''} onClick={()=>{setTab('applications');void loadApplications()}}>GESTION · CANDIDATURES</button>}</nav><button className="logout" onClick={()=>void signOut()}><LogOut size={14}/> Déconnexion</button></header>
  <div className="portal-layout">
   <aside className="profile-card"><div className="avatar operator-logo"><img src="https://cdn.picflow.com/assets/images/proxy/full/13da8b62-5943-40f5-9872-a24bd5cbb7f1.webp" alt="Logo Los Santos Police Department"/></div><h2>{staff.display_name}</h2><p>{staff.rank}</p><dl><dt>Matricule</dt><dd>{staff.badge_number||'Non défini'}</dd><dt>Division(s)</dt><dd>{divisions.length?divisions.join(' · '):'Aucune'}</dd><dt>Statut</dt><dd><span className={'tag '+(myUnit?'green':'')}>{myUnit?'EN SERVICE':'HORS SERVICE'}</span></dd></dl></aside>
   <main className="portal-main">
    {tab==='applications'?<><section className="hero-mdt"><div><p className="kicker">GESTION</p><h1>Candidatures</h1></div><Users size={52}/></section><section className="section"><div className="section-title"><b>DOSSIERS REÇUS</b><span>{applications.length}</span></div><div className="section-body units-board">{applications.map(a=><article className="unit-card" key={a.id}><div><small>{a.status.toUpperCase()}</small><h3>{a.display_name}</h3><p>{a.nationality} · {a.phone} · {a.progress}%</p></div><div className="unit-side"><button onClick={()=>setSelectedApplication(a)}>OUVRIR</button>{a.handled_by?<b>PRISE EN COMPTE</b>:<button disabled={busy} onClick={()=>void claim(a.id)}>PRENDRE EN COMPTE</button>}</div></article>)}</div></section></>:
    <><section className="hero-mdt"><div><p className="kicker">LOS SANTOS POLICE DEPARTMENT</p><h1>Prise de service</h1></div><Radio size={52}/></section>
    {!staff.badge_number&&<section className="section"><div className="section-title"><b>MATRICULE</b></div><div className="section-body badge-setup"><p>Choisis ton matricule. Il est unique et ne pourra pas être modifié depuis le panel.</p><div className="badge-row"><input value={badge} onChange={e=>setBadge(e.target.value)} placeholder="Ex. 23"/><button disabled={!badge.trim()||busy} onClick={()=>void saveBadge()}>VALIDER LE MATRICULE</button></div></div></section>}
    {staff.badge_number&&!myUnit&&<><section className="section"><div className="section-title"><b>PRISE DE SERVICE</b></div><div className="section-body duty-buttons">
      <button className="duty-choice" disabled={busy} onClick={()=>void act(()=>startService('lincoln'))}><UserRound/><span><b>PRENDRE SON SERVICE</b></span></button>
    </div></section>
    {divisions.length>0&&<section className="section"><div className="section-title"><b>SERVICE DIVISIONNAIRE</b></div><div className="section-body duty-buttons">{divisions.map(d=>{const locked=(d==='HSP'||d==='K-9')&&!completeAdam;return <button key={d} className={'duty-choice division-choice '+(locked?'locked':'')} disabled={busy||locked} onClick={()=>void act(()=>startService('division',d))}>{locked?<LockKeyhole/>:<Shield/>}<span><b>{d}</b><small>{locked?'Adam requis':''}</small></span></button>})}</div></section>}</>}
    {myUnit&&<section className="section active-duty"><div className="section-title"><b>MON UNITÉ</b></div><div className="section-body"><div className="unit-focus"><div><small>EN SERVICE</small><h2>{myUnit.name}</h2><p>{myUnit.service_type==='division'?(myUnit.division+' · '+myUnit.service_unit_members.length+' agent(s)'):(myUnit.service_unit_members.length+' / 4 agents · '+myUnit.name.split(' ')[0])}</p></div><button disabled={busy} onClick={()=>void act(()=>leaveService())}>QUITTER LE SERVICE</button></div></div></section>}
    <section className="section"><div className="section-title"><b>UNITÉS EN SERVICE</b><span>{units.length}</span></div><div className="section-body units-board">{units.length===0?<p className="empty">Aucune unité actuellement en service.</p>:units.map(u=>{const count=u.service_unit_members?.length??0;const canJoin=!myUnit&&((u.service_type!=='division'&&count<4)||(u.service_type==='division'&&divisions.includes(u.division)));return <article className="unit-card" key={u.id}><div><small>{u.service_type==='division'?u.division:u.service_type.toUpperCase()}</small><h3>{u.name}</h3><p>{u.service_unit_members?.map((m:any)=>m.staff?.display_name).filter(Boolean).join(' · ')}</p></div><div className="unit-side"><b>{count}{u.service_type!=='division'?' / 4':''}</b>{canJoin&&<button disabled={busy} onClick={()=>void act(()=>joinService(u.id))}>REJOINDRE</button>}</div></article>})}</div></section>
    </>}
    {error&&<div className="service-error">{error}</div>}
   </main>
  </div>
 </div>
}
function ApplicationFile({a,close,claim,busy}:{a:any;close:()=>void;claim:(id:string)=>Promise<void>;busy:boolean}){const yes=(v:any)=>v===true?'Oui':v===false?'Non':'—';return <div className="application-overlay" onClick={close}><article className="application-file" onClick={e=>e.stopPropagation()}><header><div><small>DOSSIER DE CANDIDATURE</small><h2>{a.display_name}</h2></div><button onClick={close}>FERMER</button></header><div className="application-sections"><section><h3>IDENTITÉ</h3><dl><dt>Nom et prénom</dt><dd>{a.display_name}</dd><dt>Nationalité</dt><dd>{a.nationality||'—'}</dd><dt>Date de naissance</dt><dd>{a.birth_date||'—'}</dd><dt>Téléphone</dt><dd>{a.phone||'—'}</dd><dt>Âge HRP</dt><dd>{a.irl_age||'—'}</dd></dl></section><section><h3>VIE PROFESSIONNELLE</h3><dl><dt>Emploi actuel</dt><dd>{yes(a.employed)}</dd>{a.employed&&<><dt>Entreprise</dt><dd>{a.company||'—'}</dd><dt>Rôle / fonction</dt><dd>{a.job_role||'—'}</dd></>}</dl></section><section><h3>EXPÉRIENCE</h3><dl><dt>Forces de l'ordre</dt><dd>{yes(a.law_enforcement_experience)}</dd></dl>{a.law_enforcement_experience&&<p>{a.experience_details||'—'}</p>}</section><section><h3>MOTIVATION</h3><p>{a.motivation||'—'}</p></section><section><h3>DOCUMENTS</h3><div className="application-docs"><Doc href={a.identity_card_url} label="CARTE D'IDENTITÉ"/><Doc href={a.driving_license_url} label="PERMIS DE CONDUIRE"/><Doc href={a.fitness_certificate_url} label="CERTIFICAT D'APTITUDE PHYSIQUE"/></div></section><section><h3>SUIVI</h3><dl><dt>Complétion</dt><dd>{a.progress}%</dd><dt>Statut</dt><dd>{a.status}</dd><dt>Envoyée le</dt><dd>{a.submitted_at?new Date(a.submitted_at).toLocaleString('fr-FR'):'—'}</dd></dl>{!a.handled_by&&<button className="wide-btn" disabled={busy} onClick={()=>void claim(a.id)}>PRENDRE EN COMPTE</button>}</section></div></article></div>}
function Doc({href,label}:{href?:string;label:string}){return href?<a href={href} target="_blank" rel="noreferrer">{label}</a>:<span>{label} · MANQUANT</span>}
