import {useEffect,useState} from 'react'
import {supabase} from '../lib/supabase'
import {Webhook,ShieldCheck,Network,CarFront,ChevronRight} from 'lucide-react'
type Page='home'|'webhooks'|'grades'|'divisions'|'vehicles'
export function SettingsCenter(){
 const [page,setPage]=useState<Page>('home'),[hook,setHook]=useState(''),[configured,setConfigured]=useState(false),[roles,setRoles]=useState<any[]>([]),[vehicles,setVehicles]=useState<any[]>([]),[error,setError]=useState(''),[saved,setSaved]=useState('')
 async function load(){const [{data:r},{data:v},{data:w}]=await Promise.all([supabase.from('discord_roles').select('id,name,discord_role_id,sort_order,active,role_groups(name,group_type,sort_order)').order('sort_order'),supabase.from('vehicle_permissions').select('*').order('sort_order'),supabase.rpc('webhook_configured')]);setRoles(r??[]);setVehicles(v??[]);setConfigured(!!w)}
 useEffect(()=>{void load()},[])
 async function saveHook(){setError('');setSaved('');const {error:e}=await supabase.rpc('set_archive_webhook',{p_url:hook});if(e)return setError(e.message);setHook('');setConfigured(true);setSaved('Webhook d’archives mis à jour.')}
 async function updateVehicle(id:string,key:string,value:any){const {error:e}=await supabase.from('vehicle_permissions').update({[key]:value,updated_at:new Date().toISOString()}).eq('id',id);if(e)setError(e.message);else await load()}
 const grades=roles.filter(r=>r.role_groups?.group_type==='rank'),divisions=roles.filter(r=>r.role_groups?.group_type==='division')
 const tiles=[['webhooks','WEBHOOKS','Archives des candidatures et rendez-vous',Webhook],['grades','GRADES','Hiérarchie, ordre et identifiants',ShieldCheck],['divisions','DIVISIONS','Unités et accès divisionnaires',Network],['vehicles','VÉHICULES & HABILITATIONS','Accès par grade ou division',CarFront]] as const
 return <div className="settings-center"><div className="settings-heading"><div><small>ADMINISTRATION</small><h1>{page==='home'?'Paramètres':tiles.find(t=>t[0]===page)?.[1]}</h1></div>{page!=='home'&&<button onClick={()=>setPage('home')}>← PARAMÈTRES</button>}</div>
 {page==='home'&&<div className="settings-tiles">{tiles.map(([id,title,desc,Icon])=><button key={id} onClick={()=>setPage(id)}><Icon/><span><b>{title}</b><small>{desc}</small></span><ChevronRight/></button>)}</div>}
 {page==='webhooks'&&<section className="settings-panel"><h2>Webhook d’archives</h2><p>L’adresse reste chiffrée côté serveur et n’est jamais réaffichée dans le panel.</p><div className={'hook-status '+(configured?'ok':'')}>{configured?'WEBHOOK CONFIGURÉ':'AUCUN WEBHOOK CONFIGURÉ'}</div><label>Nouvelle URL du webhook<input type="password" autoComplete="off" value={hook} onChange={e=>setHook(e.target.value)} placeholder="https://…/api/webhooks/…"/></label><button className="settings-save" disabled={!hook.trim()} onClick={()=>void saveHook()}>ENREGISTRER / REMPLACER</button></section>}
 {page==='grades'&&<section className="settings-panel"><h2>Grades</h2><p>Hiérarchie actuellement synchronisée avec les rôles configurés.</p><div className="settings-list">{grades.map((r,i)=><article key={r.id}><b>{String(i+1).padStart(2,'0')}</b><span><strong>{r.name}</strong><small>ID · {r.discord_role_id}</small></span><em>{r.active?'ACTIF':'INACTIF'}</em></article>)}</div></section>}
 {page==='divisions'&&<section className="settings-panel"><h2>Divisions</h2><p>Divisions reconnues pour les services et habilitations.</p><div className="settings-list">{divisions.map(r=><article key={r.id}><Network/><span><strong>{r.name}</strong><small>ID · {r.discord_role_id}</small></span><em>{r.active?'ACTIVE':'INACTIVE'}</em></article>)}</div></section>}
 {page==='vehicles'&&<section className="settings-panel"><h2>Véhicules & habilitations</h2><p>Définis le grade minimum ou la division nécessaire pour chaque véhicule.</p><div className="vehicle-settings">{vehicles.map(v=><article key={v.id}><div><strong>{v.vehicle_name}</strong><small>{v.notes||'Véhicule de service'}</small></div><div className="grade-access"><label>Mode d'accès<select value={v.grade_access_mode||'minimum'} onChange={e=>void updateVehicle(v.id,'grade_access_mode',e.target.value)}><option value="minimum">Grade minimum + supérieurs</option><option value="specific">Grades spécifiques</option></select></label>{v.grade_access_mode!=='specific'?<label>Grade minimum<select value={v.minimum_rank||''} onChange={e=>void updateVehicle(v.id,'minimum_rank',e.target.value||null)}><option value="">Tous les grades</option>{grades.map(g=><option key={g.id}>{g.name}</option>)}</select></label>:<div className="grade-checks"><small>GRADES AUTORISÉS</small>{grades.map(g=><label key={g.id}><input type="checkbox" checked={(v.allowed_grades||[]).includes(g.name)} onChange={e=>{const cur=v.allowed_grades||[];void updateVehicle(v.id,'allowed_grades',e.target.checked?[...cur,g.name]:cur.filter((x:string)=>x!==g.name))}}/>{g.name}</label>)}</div>}</div><label>Division<select value={v.division||''} onChange={e=>void updateVehicle(v.id,'division',e.target.value||null)}><option value="">Toutes</option>{divisions.map(d=><option key={d.id}>{d.name}</option>)}</select></label></article>)}</div></section>}
 {saved&&<div className="settings-message ok">{saved}</div>}{error&&<div className="settings-message">{error}</div>}</div>
}