import {useEffect,useState} from 'react'
import {supabase} from '../lib/supabase'
import {Webhook,ShieldCheck,Network,CarFront,ChevronRight} from 'lucide-react'
type Page='home'|'webhooks'|'grades'|'divisions'|'vehicles'
export function SettingsCenter(){
 const [page,setPage]=useState<Page>('home'),[roleDraft,setRoleDraft]=useState<any>({name:'',discord_role_id:''}),[vehicleDraft,setVehicleDraft]=useState<any>({vehicle_name:'',license_plate:'',notes:'',grade_access_mode:'minimum',minimum_rank:'',division:''}),[hook,setHook]=useState(''),[hookKey,setHookKey]=useState('applications'),[webhooks,setWebhooks]=useState<any[]>([]),[roles,setRoles]=useState<any[]>([]),[vehicles,setVehicles]=useState<any[]>([]),[error,setError]=useState(''),[saved,setSaved]=useState('')
 async function load(){const [{data:r},{data:v},{data:w}]=await Promise.all([supabase.from('discord_roles').select('id,group_id,name,discord_role_id,sort_order,active,role_groups(name,group_type,sort_order)').order('sort_order'),supabase.from('vehicle_permissions').select('*').order('sort_order'),supabase.rpc('webhook_category_status')]);setRoles(r??[]);setVehicles(v??[]);setWebhooks(w??[])}
 useEffect(()=>{void load()},[])
 async function saveHook(){setError('');setSaved('');const {error:e}=await supabase.rpc('set_category_webhook',{p_key:hookKey,p_url:hook});if(e)return setError(e.message);setHook('');await load();setSaved('Webhook d’archives mis à jour.')}
 async function saveRole(type:'rank'|'division',r?:any){setError('');const name=(r?.name??roleDraft.name).trim(),discord=(r?.discord_role_id??roleDraft.discord_role_id).trim();if(!name||!discord)return setError('Nom et ID Discord obligatoires.');if(r){const {error:e}=await supabase.rpc('rename_configured_role',{p_id:r.id,p_name:name,p_discord_role_id:discord});if(e)return setError(e.message)}else{const group=roles.find(x=>x.role_groups?.group_type===type)?.group_id;let gid=group;if(!gid){const {data:g,error:ge}=await supabase.from('role_groups').insert({name:type==='rank'?'Grades':'Divisions',group_type:type,sort_order:type==='rank'?10:20,active:true}).select('id').single();if(ge)return setError(ge.message);gid=g.id}const list=type==='rank'?grades:divisions;const {error:e}=await supabase.from('discord_roles').insert({group_id:gid,name,discord_role_id:discord,sort_order:(list.length+1)*10,active:true});if(e)return setError(e.message)}setRoleDraft({name:'',discord_role_id:''});await load();setSaved(type==='rank'?'Grade enregistré.':'Division enregistrée.')}
 async function deleteRole(id:string){if(!confirm('Supprimer définitivement cet élément ?'))return;const {error:e}=await supabase.rpc('delete_configured_role',{p_id:id});if(e)return setError(e.message);await load()}
 async function addVehicle(){setError('');if(!vehicleDraft.vehicle_name.trim())return setError('Nom du véhicule obligatoire.');const {error:e}=await supabase.from('vehicle_permissions').insert({vehicle_name:vehicleDraft.vehicle_name.trim(),license_plate:vehicleDraft.license_plate.trim()||null,notes:vehicleDraft.notes.trim()||null,grade_access_mode:vehicleDraft.grade_access_mode,minimum_rank:vehicleDraft.minimum_rank||null,division:vehicleDraft.division||null,allowed_grades:[],sort_order:(vehicles.length+1)*10,active:true});if(e)return setError(e.message);setVehicleDraft({vehicle_name:'',license_plate:'',notes:'',grade_access_mode:'minimum',minimum_rank:'',division:''});await load();setSaved('Véhicule ajouté.')}
 async function deleteVehicle(id:string){if(!confirm('Supprimer définitivement ce véhicule ?'))return;const {error:e}=await supabase.from('vehicle_permissions').delete().eq('id',id);if(e)return setError(e.message);await load()}
 async function updateVehicle(id:string,key:string,value:any){const {error:e}=await supabase.from('vehicle_permissions').update({[key]:value,updated_at:new Date().toISOString()}).eq('id',id);if(e)setError(e.message);else await load()}
 const grades=roles.filter(r=>r.role_groups?.group_type==='rank'),divisions=roles.filter(r=>r.role_groups?.group_type==='division')
 const tiles=[['webhooks','WEBHOOKS','Archives des candidatures et rendez-vous',Webhook],['grades','GRADES','Hiérarchie, ordre et identifiants',ShieldCheck],['divisions','DIVISIONS','Unités et accès divisionnaires',Network],['vehicles','VÉHICULES & HABILITATIONS','Accès par grade ou division',CarFront]] as const
 return <div className="settings-center"><div className="settings-heading"><div><small>ADMINISTRATION</small><h1>{page==='home'?'Paramètres':tiles.find(t=>t[0]===page)?.[1]}</h1></div>{page!=='home'&&<button onClick={()=>setPage('home')}>← PARAMÈTRES</button>}</div>
 {page==='home'&&<div className="settings-tiles">{tiles.map(([id,title,desc,Icon])=><button key={id} onClick={()=>setPage(id)}><Icon/><span><b>{title}</b><small>{desc}</small></span><ChevronRight/></button>)}</div>}
 {page==='webhooks'&&<section className="settings-panel"><h2>Webhooks par catégorie</h2><p>Chaque catégorie possède son propre webhook Discord. Les URL restent chiffrées et ne sont jamais réaffichées.</p><div className="webhook-category-grid">{webhooks.map(w=><button key={w.key} className={hookKey===w.key?'active':''} onClick={()=>{setHookKey(w.key);setHook('')}}><Webhook/><span><b>{w.label}</b><small>{w.description}</small></span><em className={w.configured?'ok':''}>{w.configured?'CONFIGURÉ':'À CONFIGURER'}</em></button>)}</div><label>Webhook · {webhooks.find(w=>w.key===hookKey)?.label||hookKey}<input type="password" autoComplete="off" value={hook} onChange={e=>setHook(e.target.value)} placeholder="https://…/api/webhooks/…"/></label><button className="settings-save" disabled={!hook.trim()} onClick={()=>void saveHook()}>ENREGISTRER / REMPLACER</button></section>}
 {page==='grades'&&<RoleEditor title="Grades" type="rank" items={grades} draft={roleDraft} setDraft={setRoleDraft} save={saveRole} remove={deleteRole}/>} 
 {page==='divisions'&&<RoleEditor title="Divisions" type="division" items={divisions} draft={roleDraft} setDraft={setRoleDraft} save={saveRole} remove={deleteRole}/>} 
 {page==='vehicles'&&<section className="settings-panel"><h2>Véhicules & habilitations</h2><p>Ajoute, modifie ou supprime les véhicules et leurs habilitations.</p><div className="admin-create"><input placeholder="Nom du véhicule" value={vehicleDraft.vehicle_name} onChange={e=>setVehicleDraft((x:any)=>({...x,vehicle_name:e.target.value}))}/><input placeholder="Plaque d'immatriculation" value={vehicleDraft.license_plate} onChange={e=>setVehicleDraft((x:any)=>({...x,license_plate:e.target.value}))}/><input placeholder="Notes" value={vehicleDraft.notes} onChange={e=>setVehicleDraft((x:any)=>({...x,notes:e.target.value}))}/><button onClick={()=>void addVehicle()}>AJOUTER LE VÉHICULE</button></div><div className="vehicle-settings">{vehicles.map(v=><article key={v.id}><div className="vehicle-admin-head"><input value={v.vehicle_name} onChange={e=>setVehicles(x=>x.map(y=>y.id===v.id?{...y,vehicle_name:e.target.value}:y))} onBlur={()=>void updateVehicle(v.id,'vehicle_name',v.vehicle_name)}/><button onClick={()=>void deleteVehicle(v.id)}>SUPPRIMER</button></div><label>Plaque d'immatriculation<input value={v.license_plate||''} placeholder="Ex. LSPD-01" onChange={e=>setVehicles(x=>x.map(y=>y.id===v.id?{...y,license_plate:e.target.value}:y))} onBlur={()=>void updateVehicle(v.id,'license_plate',v.license_plate||null)}/></label><label>Notes<input value={v.notes||''} onChange={e=>setVehicles(x=>x.map(y=>y.id===v.id?{...y,notes:e.target.value}:y))} onBlur={()=>void updateVehicle(v.id,'notes',v.notes||null)}/></label><div className="grade-access"><label>Mode d'accès<select value={v.grade_access_mode||'minimum'} onChange={e=>void updateVehicle(v.id,'grade_access_mode',e.target.value)}><option value="minimum">Grade minimum + supérieurs</option><option value="specific">Grades spécifiques</option></select></label>{v.grade_access_mode!=='specific'?<label>Grade minimum<select value={v.minimum_rank||''} onChange={e=>void updateVehicle(v.id,'minimum_rank',e.target.value||null)}><option value="">Tous les grades</option>{grades.map(g=><option key={g.id}>{g.name}</option>)}</select></label>:<div className="grade-checks"><small>GRADES AUTORISÉS</small>{grades.map(g=><label key={g.id}><input type="checkbox" checked={(v.allowed_grades||[]).includes(g.name)} onChange={e=>{const cur=v.allowed_grades||[];void updateVehicle(v.id,'allowed_grades',e.target.checked?[...cur,g.name]:cur.filter((x:string)=>x!==g.name))}}/>{g.name}</label>)}</div>}</div><label>Division<select value={v.division||''} onChange={e=>void updateVehicle(v.id,'division',e.target.value||null)}><option value="">Toutes</option>{divisions.map(d=><option key={d.id}>{d.name}</option>)}</select></label></article>)}</div></section>} {saved&&<div className="settings-message ok">{saved}</div>}{error&&<div className="settings-message">{error}</div>}</div>
}
function RoleEditor({title,type,items,draft,setDraft,save,remove}:{title:string;type:'rank'|'division';items:any[];draft:any;setDraft:(x:any)=>void;save:(t:'rank'|'division',r?:any)=>Promise<void>;remove:(id:string)=>Promise<void>}){const [edits,setEdits]=useState<Record<string,any>>({});return <section className="settings-panel"><h2>{title}</h2><p>Modifie le nom ou l’ID Discord, ajoute ou supprime des éléments.</p><div className="admin-create"><input placeholder={type==='rank'?'Nom du grade':'Nom de la division'} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><input placeholder="ID du rôle Discord" value={draft.discord_role_id} onChange={e=>setDraft({...draft,discord_role_id:e.target.value})}/><button onClick={()=>void save(type)}>AJOUTER</button></div><div className="settings-list editable">{items.map((r,i)=>{const x=edits[r.id]||r;return <article key={r.id}><b>{String(i+1).padStart(2,'0')}</b><span><input value={x.name} onChange={e=>setEdits({...edits,[r.id]:{...x,name:e.target.value}})}/><input value={x.discord_role_id} onChange={e=>setEdits({...edits,[r.id]:{...x,discord_role_id:e.target.value}})}/></span><div className="row-actions"><button onClick={()=>void save(type,x)}>ENREGISTRER</button><button onClick={()=>void remove(r.id)}>SUPPRIMER</button></div></article>})}</div></section>}
