const gradeGroups=[
 {title:'Rookie',vehicles:['Patrouilleuse (Stanier)','Speedo Police']},
 {title:'Hommes du rang',vehicles:['Patrouilleuse (Stanier)','Gauntlet Police','Bison (4X4)','Speedo Police']},
 {title:'Sous Officiers',vehicles:['Patrouilleuse (Stanier)','Gauntlet Police','Buffalo STX Police','Bison (4X4)','Vapid Scout (4X4)','Speedo Police']},
 {title:'Officiers',vehicles:['Patrouilleuse (Stanier)','Gauntlet Police','Buffalo STX Police','Bison (4X4)','Vapid Scout (4X4)','Terminus Police (4X4)','Speedo Police'],note:'Buffalo STX banalisée pour les déplacements autres que des patrouilles.'},
 {title:'État-Major',vehicles:['Vigero ZX Police']}
]
const unitGroups=[
 {title:'Traffic Division',vehicles:['BF 400 Police','Hakuchou Police','Buffalo STX Police','Coquette Police']},
 {title:'Special Weapons And Tactics',vehicles:['Bearcat S.W.A.T','Buffalo STX (covering SWAT)','Fourgon anti-émeute RIOT','Insurgent']},
 {title:'Street Crime Unit',vehicles:['Véhicules banalisés SCU du garage','Véhicules de service accessibles']}
]
export function VehicleAssignments({onBack}:{onBack:()=>void}){return <div className="vehicle-page"><header className="rules-page-top"><button onClick={onBack}>← RÈGLEMENT</button><b>VÉHICULES — ATTRIBUTION PAR GRADE</b><span>L.S.P.D</span></header><main className="vehicle-sheet"><section className="vehicle-cover"><small>LOS SANTOS POLICE DEPARTMENT</small><h1>Véhicules<br/><span>Attribution par grade</span></h1><p>« Protéger et Servir »</p></section><section className="vehicle-intro"><h2>Répartition des véhicules de fonction par grades et unités</h2><p>Le manuel de répartition des véhicules de fonction est destiné à tous les agents de police du département afin de prendre les véhicules autorisés en fonction de la situation. Certains véhicules sont attribués pour toute la LSPD à partir de certains grades. Ces grades sont des grades paliers qui déterminent quel véhicule est disponible à partir de quel grade.</p><p>Les véhicules déjà débloqués peuvent donc être utilisés par les grades supérieurs. Les véhicules réservés aux unités ne doivent être utilisés qu’en cas de patrouilles d’unités sous directives du dispatch. Certaines dérogations concernant la sortie des véhicules peuvent être accordées par des membres de l’État-Major.</p></section><section className="vehicle-section"><div className="vehicle-section-title"><small>01</small><h2>Attributions par grade</h2></div><div className="vehicle-grid">{gradeGroups.map(g=><article className="vehicle-card" key={g.title}><h3>{g.title}</h3><ul>{g.vehicles.map(v=><li key={v}>{v}</li>)}</ul>{g.note&&<p>{g.note}</p>}</article>)}</div></section><section className="vehicle-section"><div className="vehicle-section-title"><small>02</small><h2>Attribution par unité</h2></div><div className="vehicle-grid units">{unitGroups.map(g=><article className="vehicle-card" key={g.title}><h3>{g.title}</h3><ul>{g.vehicles.map(v=><li key={v}>{v}</li>)}</ul></article>)}</div></section></main></div>}
